package com.sunlines.qi.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sunlines.qi.entity.Example;

import com.sunlines.qi.dao.ExampleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exampleDaoConfig;

    private final ExampleDao exampleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exampleDaoConfig = daoConfigMap.get(ExampleDao.class).clone();
        exampleDaoConfig.initIdentityScope(type);

        exampleDao = new ExampleDao(exampleDaoConfig, this);

        registerDao(Example.class, exampleDao);
    }
    
    public void clear() {
        exampleDaoConfig.clearIdentityScope();
    }

    public ExampleDao getExampleDao() {
        return exampleDao;
    }

}
